"""Delete notification type

Revision ID: b1281769f205
Revises: 6163d1441cf5
Create Date: 2024-12-22 12:31:48.446238

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'b1281769f205'
down_revision = '6163d1441cf5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix__notification__type', table_name='notification')
    op.create_unique_constraint(op.f('uq__notification__id'), 'notification', ['id'])
    op.drop_column('notification', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('uq__notification__id'), 'notification', type_='unique')
    op.create_index('ix__notification__type', 'notification', ['type'], unique=False)
    # ### end Alembic commands ###
