"""empty message

Revision ID: 11068c0020f3
Revises: b88b6c6f4ed6
Create Date: 2024-12-20 09:45:57.448974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '11068c0020f3'
down_revision = 'b88b6c6f4ed6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('notify_ts', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('sent_ts', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk__notification__event_id__event')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__notification')),
    sa.UniqueConstraint('id', name=op.f('uq__notification__id'))
    )
    op.create_index(op.f('ix__notification__event_id'), 'notification', ['event_id'], unique=False)
    op.create_index(op.f('ix__notification__status'), 'notification', ['status'], unique=False)
    op.create_index(op.f('ix__notification__workflow_id'), 'notification', ['workflow_id'], unique=True)
    op.add_column('event', sa.Column('status', sa.String(), nullable=False))
    op.add_column('event', sa.Column('reschedule_timedelta', sa.Interval(), nullable=True))
    op.drop_index('ix__event__type', table_name='event')
    op.create_index(op.f('ix__event__status'), 'event', ['status'], unique=False)
    op.drop_column('event', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix__event__status'), table_name='event')
    op.create_index('ix__event__type', 'event', ['type'], unique=False)
    op.drop_column('event', 'reschedule_timedelta')
    op.drop_column('event', 'status')
    op.drop_index(op.f('ix__notification__workflow_id'), table_name='notification')
    op.drop_index(op.f('ix__notification__status'), table_name='notification')
    op.drop_index(op.f('ix__notification__event_id'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
